<?php

$lan = array(

'Please select a message to display' => 'Please select a message to display',
'Attachments for this message' => 'Attachments for this message',
'No attachments' => 'No attachments',
'Filename' => 'Filename',
'Size' => 'Size',
'Mime Type' => 'Mime Type',
'Lists this message has been sent to' => 'Lists this message has been sent to',
'Send this (same) message to (a) new list(s)' => 'Send this (same) message to (a) new list(s)',
'List is Active' => 'List is Active',
'List is not Active' => 'List is not Active',
'<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the &quot;Requeue&quot; function.' => '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the &quot;Requeue&quot; function.',
'Resend' => 'Resend',
'id' => 'id',
'fromfield' => 'from field',
'tofield' => 'to field',
'replyto' => 'reply to',
'textmessage' => 'textmessage',
'footer' => 'footer',
'embargo' => 'embargo',
'repeatinterval' => 'repeatinterval',
'userselection' => 'userselection',
'htmlformatted' => 'htmlformatted',
'sendformat' => 'sendformat',
'template' => 'template',
'astext' => 'as text',
'ashtml' => 'as html',
'aspdf' => 'as pdf',
'astextandpdf' => 'as text and pdf',
'bouncecount' => 'bounce count',
'sendstart' => 'send start',
'rsstemplate' => 'RSS template',
'edit this message' => 'Edit this message',
'No such message' => 'No such message',
'<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.',
'repeatuntil' => 'repeatuntil',
'requeueinterval' => 'requeueinterval',
'processed' => 'processed',
'requeueuntil' => 'requeueuntil',
);
?>