<?php

$lan = array(

'htmlusedwarning' => 'Warning: You indicated the content was not HTML, but there were  some HTML  tags in it. This  may  cause  errors',
'adding' => 'Adding',
'longmimetype' => 'Mime Type is longer than 255 characters, this is trouble',
'addingattachment' => 'Added attachment ',
'uploadfailed' => 'Uploaded file not properly received, empty file',
'saved' => 'Message saved',
'added' => 'Message added',
'queued' => 'Message queued for send',
'errorsubject' => 'Sorry, you used invalid characters in the Subject field.',
'errorfrom' => 'Sorry, you used invalid characters in the From field.',
'enterfrom' => 'Please enter a from line.',
'entermessage' => 'Please enter a message',
'entersubject' => 'Please enter a subject',
'duplicateattribute' => 'Error: you can use an attribute in one rule only',
'selectlist' => 'Please select the list(s) to send the campaign to',
'notargetemail' => 'No target email addresses listed for testing.',
'emailnotfound' => 'Email address not found to send test message.',
'sentemailto' => 'Sent test mail to',
'removedattachment' => 'Removed Attachment ',
'existingcriteria' => 'Existing criteria',
'remove' => 'Remove',
'calculating' => 'Calculating',
'calculate' => 'Calculate',
'content' => 'Content',
'format' => 'Format',
'attach' => 'Attach',
'scheduling' => 'Scheduling',
'criteria' => 'Criteria',
'unsavedchanges' => 'Warning, You have unsaved changes\nClick OK to continue, or Cancel to stay on this page\nso you can save the changes.',
'whatisprepare' => 'What is prepare a message',
'fromline' => 'From Line',
'embargoeduntil' => 'Embargoed Until',
'repeatevery' => 'Repeat campaign every',
'norepetition' => 'no repetition',
'hour' => 'Hour',
'day' => 'Day',
'week' => 'Week',
'repeatuntil' => 'Repeat Until',
'autodetect' => 'Auto Detect',
'sendas' => 'Send As',
'pdf' => 'PDF',
'textandpdf' => 'Text and PDF',
'usetemplate' => 'Use Template',
'selectone' => 'select one',
'rssintro' => 'If you want to use this message as the template for sending RSS feeds
    select the frequency it should be used for and use [RSS] in your message to indicate where the list of items needs to go.',
'plaintextversion' => 'Plain text version of message',
'messagefooter' => 'Footer',
'messagefooterexplanation1' => 'Use <b>[UNSUBSCRIBE]</b> to insert the personal unsubscribe URL for each user.',
'messagefooterexplanation2' => 'Use <b>[PREFERENCES]</b> to insert the personal URL for a user to update their details.',
'messagefooterexplanation3' => 'Use <b>[FORWARD]</b> to add a personalised URL to forward the message to someone else.',
'messagefooterexplanation' => 'Use <b>[UNSUBSCRIBE]</b> to insert the personal unsubscribe URL for each user.
  <br/>Use <b>[PREFERENCES]</b> to insert the personal URL for a user to update their details.',
'addattachments' => 'Add attachments to your campaign',
'uploadlimits' => 'The upload has the following limits set by the server',
'maxtotaldata' => 'Maximum size of total data being sent to the server',
'maxfileupload' => 'Maximum size of each individual file',
'currentattachments' => 'Current Attachments',
'newattachment' => 'New Attachment',
'addandsave' => 'Add (and save)',
'pathtofile' => 'Path to file on server',
'attachmentdescription' => 'Description of attachment',
'delchecked' => 'Delete Checked',
'sendtestmessage' => 'Send Test Message',
'toemailaddresses' => ' to email address(es)',
'sendtestexplain' => '(comma separated addresses - all must be users)',
'criteriaexplanation' => '
        <p class="information"><b>Select the criteria for this message:</b></p>
        <ol>
        <li>to use a criteria, check the box next to it</li>
        <li>then check the radio button next to the attribute you want to use</li>
        <li>then choose the values of the attributes you want to send the message to
        <i>Note:</i> Messages will be sent to people who fit to <i>Criteria 1</i> <b>AND</b> <i>Criteria 2</i> etc </li>
        </ol>
        ',
'criterion' => 'Criterion',
'usethisone' => 'Use this one',
'nocriteria' => 'There are currently no attributes available to use for sending. The campaign will go to any user on the lists selected',
'saveasdraft' => 'Save as Draft',
'selectlists' => 'Please select the lists you want to send it to',
'selectexcludelist' => 'Select the lists to be excluded.',
'excludelistexplain' => 'The campaign will go to users who are a member of the lists above,
    unless they are a member of one of the lists you select here.',
'nolistsavailable' => 'Sorry, there are currently no lists available',
'sendmessage' => 'Send Campaign',
'warnnopearhttprequest' => 'You are trying to send a remote URL, but PEAR::HTTP/Request is not available, so this will fail',
'use [FORWARD] to add a personalised URL to forward the message to someone else.' => 'use <b>[FORWARD]</b> to add a personalised URL to forward the message to someone else.',
'PGP' => 'PGP',
'Sign message' => 'Sign message',
'Select email to sign with' => 'Select email to sign with',
'Enter pass phrase' => 'Enter pass phrase',
'Encrypt message' => 'Encrypt message',
'When a message cannot be encrypted because the public key cannot be found' => 'When a message cannot be encrypted because the public key cannot be found',
'Send it anyway, but unencrypted' => 'Send it anyway, but unencrypted',
'Do not send it' => 'Do not send it',
'No RSS' => 'No RSS',
'start a new message' => 'start a new campaign',
'Choose an existing draft message to work on' => 'Choose an existing draft campaign to work on',
'add' => 'add',
'Send your message from' => 'Send your message from',
'a URL (website)' => 'a URL (website)',
'Enter it here' => 'Enter it here',
'URL' => 'URL',
'Time is Based on the Server Time' => 'Time is Based on the Server Time',
'Current Server Time is' => 'Current Server Time is',
'requeueevery' => 'requeue every',
'norequeueing' => 'do not requeue',
'add Google tracking code' => 'add Google tracking code',
'Estimated size of mailout' => 'Estimated size of mailout',
'campaigns deleted' => 'campaigns deleted',
'campaign deleted' => 'campaign deleted',
'Draft messages' => 'Draft campaigns',
'Forward' => 'Forward',
'Misc' => 'Misc',
'RSS' => 'RSS',
'When a user forwards to a friend, the friend will receive this message instead of the one on the content tab.' => 'When a user forwards to a friend, the friend will receive this message instead of the one on the content tab.',
'forwardfooter' => 'forwardfooter',
'messageforwardfooterexplanation' => 'The footer of the forwarded message.',
'email to alert when sending of this message starts' => 'email to alert when sending of this message starts',
'separate multiple with a comma' => 'separate multiple with a comma',
'email to alert when sending of this message has finished' => 'email to alert when sending of this message has finished',
'No emails capable of signing' => 'No emails capable of signing',
'You should not paste the results of a test email back into the editor' => 'You should not paste the results of a test email back into the editor',
'This will break the click track statistics.' => 'This will break the click track statistics.',
'requeueuntil' => 'requeue until',
'subject missing' => 'subject missing',
'message content missing' => 'message content missing',
'destination lists missing' => 'destination lists missing',
'filename' => 'filename',
'size' => 'size',
'file' => 'file',
'When a user forwards to a friend," .
  " the friend will receive this message instead of the one on the content tab.' => 'When a user forwards to a friend," .
  " the friend will receive this message instead of the one on the content tab.',
'textandhtml' => 'text and html',
'or' => 'or',
'Estimated size of HTML email' => 'Estimated size of HTML email',
'Estimated size of text email' => 'Estimated size of text email',
'About %d users to receive HTML and %s users to receive text version of email' => 'About %d users to receive HTML and %s users to receive text version of email',
'From missing' => 'From missing',
);
?>