<?php 
$lan = array(

  'add_list' => 'Lägg till en lista', //duplicated in import1_text
  'cant_connect' => 'kan inte ansluta till extern databas',
  'no_users_to_copy' => 'Inga medlemmar att kopiera, är prefixet korrekt?',
  'remote_server' => 'Vänligen ange detaljer för den externa servern',
  'server' => 'Server:',
  'user' => 'Medlem:',
  'passwd' => 'Lösenord:',
  'database' => 'Databasnamn:',
  'table_prefix' => 'Tabellprefix:',
  'usertable_prefix' => 'Medlemstabellprefix:',
  'select_lists' => 'Välj listorna som e-postadresserna ska läggas till i',
  'copy_lists' => 'Kopiera listor från extern server (listor matchas genom namn)',
  'users_as_html' => 'Markera nya medlemmar som HTML-mottagare:',
  'info_overwrite_existing' => 'Om du kryssar för "Skriv över befintliga"  kommer information om en medlem i databasen skrivas över med den importerade informationen. Medlemmar matchas genom dess e-postadresser.',
  'overwrite_existing' => 'Skriv över befintliga:',
  'connecting_remote' => 'Ansluter till extern databas',
  'getting_data' => 'Hämtar data från ',
  'remote_version' => 'Extern version är',
  'remote_has' => 'Extern version har',
  'users' => 'medlemmar',
  'lists' => 'listor',
  'copying_lists' => 'Kopierar listor',
  'list' => 'Lista',
  'exists_locally' => 'finns lokalt',
  'created_locally' => 'skapades lokalt',
  'remote_list' => 'Extern lista',
  'not_created' => 'skapades inte',
  'copying_attribs' => 'Kopierar attribut',
  'attrib' => 'Attribut',
  'copying_users' => 'Kopierar medlemmar',
  'overwrite_local' => 'skriver över lokal data',
  'keep_local' => 'behåller lokal data',
  'new_user' => 'är en ny medlem',
  'no_mapped_attrib' => 'Fel, inga länkade attribut för',
  'no_local_list' => 'Fel, ingen lokal lista definierad för',
  'No lists available' => 'Inga listor finns tillgängliga',
  'Done' => 'Färdig',
  'new users' => 'nya medlemmar',
  'and' => 'och',
  'existing users' => 'befintliga medlemmar',
  'continue' => 'Fortsätt',

);
?>
