<?PHP

$inst_tab = '';
$tabnum = '';  

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_admin (
  record tinyint(10) NOT NULL auto_increment,
  adminid varchar(64) NOT NULL default '',
  adminpass varchar(64) NOT NULL default '',
  super int(1) NOT NULL default '0',
  date date NOT NULL default '0000-00-00',
  time time NOT NULL default '00:00:00',
  email varchar(255) NOT NULL,
  PRIMARY KEY  (record)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_ads (
  id int(255) NOT NULL auto_increment,
  grp int(255) NOT NULL default '0',
  title varchar(64) NOT NULL default '',
  text text NOT NULL,
  hits int(255) NOT NULL default '0',
  conv mediumint(255) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_affiliates (
  id int(10) NOT NULL auto_increment,
  username varchar(64) NOT NULL default '',
  password varchar(64) NOT NULL default '',
  approved int(1) NOT NULL default '0',
  suspended int(1) NOT NULL default '0',
  payable varchar(64) NOT NULL default '',
  tax_id_ssn blob NOT NULL,
  company varchar(128) NOT NULL default '',
  f_name varchar(64) NOT NULL default '',
  l_name varchar(64) NOT NULL default '',
  email varchar(64) NOT NULL default '',
  address_1 varchar(64) NOT NULL default '',
  address_2 varchar(64) NOT NULL default '',
  city varchar(64) NOT NULL default '',
  state varchar(40) NOT NULL default '',
  zip varchar(20) NOT NULL default '',
  country varchar(64) NOT NULL default '',
  phone varchar(40) NOT NULL default '',
  fax varchar(40) NOT NULL default '',
  url varchar(128) NOT NULL default '',
  pp int(2) NOT NULL default '0',
  paypal varchar(64) NOT NULL default '',
  tier int(255) NOT NULL default '0',
  hits_in int(255) NOT NULL default '0',
  conv int(255) NOT NULL default '0',
  type int(5) NOT NULL default '0',
  level int(5) NOT NULL default '0',
  a1 int(1) NOT NULL default '1',
  a2 int(1) NOT NULL default '1',
  a3 int(1) NOT NULL default '1',
  alert int(1) NOT NULL default '0',
  installed int(1) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_alert (
  ca_use int(1) NOT NULL default '0',
  ca_show int(1) NOT NULL default '0',
  ca_adm int(1) NOT NULL default '0',
  ca_adm_tier int(1) NOT NULL default '0',
  ca_adm_rec int(1) NOT NULL default '0',
  version varchar(10) NOT NULL default ''
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_alternate_links (
  id int(255) NOT NULL auto_increment,
  aff_id int(255) NOT NULL default '0',
  url text NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_archive (
  record int(100) NOT NULL auto_increment,
  id int(255) NOT NULL default '0',
  date date NOT NULL default '0000-00-00',
  time time NOT NULL default '00:00:00',
  payment decimal(10,2) NOT NULL default '0.00',
  tier int(255) NOT NULL default '0',
  top_tier_tag int(1) NOT NULL default '0',
  bonus int(1) NOT NULL default '0',
  stamp bigint(12) unsigned zerofill NOT NULL default '000000000000',
  recurring int(255) NOT NULL default '0',
  tier_id int(255) NOT NULL default '0',
  tracking varchar(64) NOT NULL default '',
  op1 varchar(64) NOT NULL default '',
  op2 varchar(64) NOT NULL default '',
  op3 varchar(64) NOT NULL default '',
  amount decimal(10,2) NOT NULL default '0.00',
  type int(1) NOT NULL default '0',
  split varchar(128) NOT NULL default '',
  profile int(2) NOT NULL default '0',
  tid1 varchar(255) NOT NULL,
  tid2 varchar(255) NOT NULL,
  tid3 varchar(255) NOT NULL,
  tid4 varchar(255) NOT NULL,
  target_url varchar(255) NOT NULL,
  sub_id varchar(64) NOT NULL,
  payment_rec varchar(255) NOT NULL,
  referring_url varchar(255) NOT NULL,
  KEY record (record)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_banners (
  number int(3) NOT NULL auto_increment,
  grp int(10) NOT NULL default '0',
  size1 varchar(10) NOT NULL default '',
  size2 int(10) NOT NULL default '0',
  image varchar(64) NOT NULL default '',
  description text NOT NULL,
  hits int(255) NOT NULL default '0',
  conv int(255) NOT NULL default '0',
  PRIMARY KEY  (number)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_colors (
  cp_head_back varchar(7) NOT NULL default '',
  cp_foot_back varchar(7) NOT NULL default '',
  page_border varchar(7) NOT NULL default '',
  light_cells varchar(7) NOT NULL default '',
  lighter_cells varchar(7) NOT NULL default '',
  mid_cells varchar(7) NOT NULL default '',
  left_column varchar(7) NOT NULL default '',
  top_bot_links varchar(7) NOT NULL default '',
  alt_links varchar(7) NOT NULL default '',
  top_bot_text varchar(7) NOT NULL default '',
  logged_menu varchar(7) NOT NULL default '',
  menu_links varchar(7) NOT NULL default '',
  page_back varchar(7) NOT NULL default '',
  page_links varchar(7) NOT NULL default '',
  red_text varchar(7) NOT NULL default '',
  white_back varchar(7) NOT NULL default '',
  section_head_txt varchar(7) NOT NULL default '',
  dim_font varchar(7) NOT NULL default '',
  tag_color varchar(7) NOT NULL default ''
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_config (
  sitename varchar(128) NOT NULL default '',
  siteurl varchar(255) NOT NULL default '',
  base_url varchar(255) NOT NULL default '',
  full_path varchar(255) NOT NULL default '',
  cookie_url varchar(128) NOT NULL default '',
  main_logo varchar(128) NOT NULL default '',
  account_approval int(1) NOT NULL default '0',
  sale_approval_1 int(1) NOT NULL default '0',
  sale_approval_2 int(1) NOT NULL default '0',
  sale_approval_3 int(1) NOT NULL default '0',
  welcome_email int(1) NOT NULL default '0',
  balance decimal(10,2) NOT NULL default '0.00',
  startnumber int(255) NOT NULL default '0',
  initialbalance decimal(10,2) NOT NULL default '0.00',
  paytype int(1) NOT NULL default '0',
  ap_1 int(1) NOT NULL default '0',
  ap_2 int(1) NOT NULL default '0',
  ap_3 int(1) NOT NULL default '0',
  def_pay int(1) NOT NULL default '0',
  mailadmin int(1) NOT NULL default '0',
  currency varchar(10) NOT NULL default '',
  cur_sym char(2) NOT NULL default '',
  notify int(1) NOT NULL default '0',
  paypal int(1) NOT NULL default '0',
  paypal_cur char(3) NOT NULL,
  force_paypal int(1) NOT NULL default '0',
  paypal_rate decimal(10,6) NOT NULL default '0.000000',
  use_rate int(1) NOT NULL default '0',
  paypal_return varchar(128) NOT NULL default '',
  browse int(1) NOT NULL default '0',
  sale_notify int(1) NOT NULL default '0',
  sale_notify_ppc int(1) NOT NULL default '0',
  sale_notify_affiliate int(1) NOT NULL default '0',
  sale_notify_affiliate_ppc int(1) NOT NULL default '0',
  payday varchar(5) NOT NULL default '',
  delay_minutes int(5) NOT NULL default '0',
  second_tier int(1) NOT NULL default '0',
  tier_payout decimal(10,2) NOT NULL default '0.00',
  tier_payout_flat decimal(10,2) NOT NULL default '0.00',
  max_size int(255) NOT NULL default '0',
  allow_rec int(10) NOT NULL default '0',
  aff_lock int(1) NOT NULL default '0',
  expire int(20) NOT NULL default '0',
  expire_type int(1) NOT NULL default '0',
  expire_stamp int(40) NOT NULL default '0',
  sessions int(1) NOT NULL default '0',
  offline int(1) NOT NULL default '0',
  offline_loc varchar(128) default NULL,
  offline_send varchar(128) default NULL,
  offline_tag varchar(64) default NULL,
  rew_notify int(11) NOT NULL default '0',
  rew_admin_notify int(11) NOT NULL default '0',
  links int(1) NOT NULL default '0',
  mod_later int(1) NOT NULL default '0',
  faq int(1) NOT NULL default '0',
  idev_affiliate varchar(10) NOT NULL default '0',
  link_style int(1) NOT NULL default '0',
  mark_track int(1) NOT NULL default '0',
  version varchar(20) NOT NULL default '',
  license varchar(64) NOT NULL default '',
  license_method enum('phpaudit_exec_socket','phpaudit_exec_curl','file_get_contents') NOT NULL default 'phpaudit_exec_socket',
  license_local_key blob NOT NULL,
  show_idev int(1) NOT NULL default '0',
  com_show int(1) NOT NULL default '0',
  com_show_add int(1) NOT NULL default '0',
  panel_width int(5) NOT NULL default '0',
  page_style char(1) NOT NULL default '',
  panel_align varchar(6) NOT NULL default '',
  tlinks int(1) NOT NULL default '0',
  use_keywords int(1) NOT NULL default '0',
  pend_show int(1) NOT NULL default '0',
  tpaystyle int(1) NOT NULL default '0',
  filename varchar(128) NOT NULL default '',
  use_email int(1) NOT NULL default '0',
  email_interval int(5) NOT NULL default '0',
  lead_approval int(1) NOT NULL default '0',
  secret int(25) NOT NULL default '0',
  second_contact int(1) NOT NULL default '0',
  flashcab varchar(20) NOT NULL default '',
  pass_var int(1) NOT NULL,
  use_security int(1) NOT NULL,
  ip_setting varchar(64) NOT NULL,
  admin_notify_logo int(1) NOT NULL,
  affiliate_notify_logo int(1) NOT NULL,
  sub_enable int(1) NOT NULL,
  affiliate_notify_unapproved int(1) NOT NULL,
  bk_image varchar(255) NOT NULL,
  lightbox_link_text tinytext NOT NULL,
  account_notify_affiliate_approved int(1) NOT NULL,
  fraud_type int(1) NOT NULL,
  allow_alternate int(1) NOT NULL,
  duplicate_notify int(1) NOT NULL
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_custom (
  id int(255) NOT NULL auto_increment,
  link varchar(255) NOT NULL default '',
  active int(1) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_custom_links (
  id int(255) NOT NULL auto_increment,
  aff_id int(255) NOT NULL,
  url varchar(255) NOT NULL,
  display int(1) NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_delayed (
  enabled int(1) NOT NULL default '0',
  days int(10) NOT NULL default '0',
  action int(1) NOT NULL default '0',
  KEY enabled (enabled)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_email (
  approved_subject text NOT NULL,
  approved_body text NOT NULL,
  approved_footer text NOT NULL,
  declined_subject text NOT NULL,
  declined_body text NOT NULL,
  declined_footer text NOT NULL,
  welcome_subject text NOT NULL,
  welcome_body text NOT NULL,
  admin_acct_subject text NOT NULL,
  admin_acct_body text NOT NULL,
  admin_sale_subject text NOT NULL,
  admin_sale_footer text NOT NULL,
  admin_sale_body text NOT NULL,
  comm_subject text NOT NULL,
  comm_body text NOT NULL,
  new_app_subject text NOT NULL,
  new_app_body text NOT NULL,
  friend_body text NOT NULL,
  friend_subject text NOT NULL,
  admin_rec_subject text NOT NULL,
  admin_rec_body text NOT NULL,
  admin_rew_subject text NOT NULL,
  admin_rew_body text NOT NULL,
  rew_subject text NOT NULL,
  rew_body text NOT NULL,
  admin_fail_subject text NOT NULL,
  admin_fail_body text NOT NULL,
  login_subject text NOT NULL,
  login_body text NOT NULL,
  admin_notify_logo_sub text NOT NULL,
  admin_notify_logo_body text NOT NULL,
  aff_img_app_sub text NOT NULL,
  aff_img_app_body text NOT NULL,
  aff_img_dec_sub text NOT NULL,
  aff_img_dec_body text NOT NULL,
  aff_unapprove_sub text NOT NULL,
  aff_unapprove_body text NOT NULL
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_email_interval (
  id int(255) NOT NULL auto_increment,
  aff int(255) NOT NULL default '0',
  wait int(40) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_email_settings (
  address varchar(128) NOT NULL default '',
  alternate_email_address varchar(128) NOT NULL default '',
  from_name varchar(64) NOT NULL default '',
  signature text NOT NULL,
  transport int(1) NOT NULL default '0',
  smtp_port int(5) NOT NULL default '0',
  smtp_host varchar(64) NOT NULL default '',
  smtp_auth varchar(10) NOT NULL default '',
  smtp_user varchar(64) NOT NULL default '',
  smtp_pass varchar(64) NOT NULL default '',
  PRIMARY KEY  (address)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_email_templates (
  id int(255) NOT NULL auto_increment,
  name varchar(128) NOT NULL default '',
  grp int(255) NOT NULL default '0',
  content longtext NOT NULL,
  hits int(255) NOT NULL default '0',
  conv int(255) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_faq (
  id int(255) NOT NULL auto_increment,
  question text NOT NULL,
  answer text NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_form_custom_data (
  id int(255) NOT NULL auto_increment,
  affid int(255) NOT NULL default '0',
  custom_id int(255) NOT NULL default '0',
  custom_value varchar(255) NOT NULL default '',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_form_fields (
  id int(11) NOT NULL auto_increment,
  used int(11) NOT NULL default '0',
  req int(11) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_form_fields_custom (
  id int(255) NOT NULL auto_increment,
  name varchar(64) NOT NULL default '',
  title varchar(128) NOT NULL default '',
  def_value varchar(128) NOT NULL default '',
  req int(1) NOT NULL default '0',
  sort int(255) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_groups (
  id int(255) NOT NULL auto_increment,
  name varchar(128) NOT NULL default '',
  contains int(10) NOT NULL default '0',
  ads int(10) NOT NULL default '0',
  links int(10) NOT NULL default '0',
  hads int(10) NOT NULL default '0',
  location varchar(255) NOT NULL default '',
  etemps int(10) NOT NULL default '0',
  peels int(10) NOT NULL default '0',
  lightboxes int(10) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_groups_exclude (
  id int(255) NOT NULL,
  affiliate_id int(255) NOT NULL
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_htmlads (
  id int(255) NOT NULL auto_increment,
  name varchar(128) NOT NULL default '',
  grp int(255) NOT NULL default '0',
  html_code text NOT NULL,
  hits int(255) NOT NULL default '0',
  conv int(255) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_integration (
  type int(1) NOT NULL default '0',
  auto int(1) NOT NULL default '0',
  manual int(1) NOT NULL default '0',
  idev_vartotal varchar(64) NOT NULL default '',
  idev_order varchar(64) NOT NULL default '',
  idev_var1 varchar(64) NOT NULL default '',
  cart_var1 text NOT NULL,
  use_var1 int(1) NOT NULL default '0',
  tag_var1 varchar(64) NOT NULL default '',
  idev_var2 varchar(64) NOT NULL default '',
  cart_var2 text NOT NULL,
  use_var2 int(1) NOT NULL default '0',
  tag_var2 varchar(64) NOT NULL default '',
  idev_var3 varchar(64) NOT NULL default '',
  cart_var3 text NOT NULL,
  use_var3 int(1) NOT NULL default '0',
  tag_var3 varchar(64) NOT NULL default ''
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_invoice (
  company varchar(255) NOT NULL default '',
  ad1 varchar(100) NOT NULL default '',
  ad2 varchar(50) NOT NULL default '',
  city varchar(100) NOT NULL default '',
  state varchar(50) NOT NULL default '',
  zip varchar(20) NOT NULL default '',
  country varchar(3) NOT NULL,
  note varchar(255) NOT NULL default '',
  aff_inv int(1) NOT NULL default '0'
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_iptracking (
  id int(255) NOT NULL auto_increment,
  acct_id int(255) NOT NULL default '0',
  ip varchar(64) NOT NULL default '',
  refer varchar(128) NOT NULL default '',
  stamp int(40) NOT NULL default '0',
  hit_time varchar(128) NOT NULL default '',
  hit_date varchar(128) NOT NULL default '',
  src1 int(1) NOT NULL default '0',
  src2 int(10) NOT NULL default '0',
  split varchar(128) NOT NULL default '',
  sub_id varchar(64) NOT NULL,
  tid1 varchar(64) NOT NULL,
  tid2 varchar(64) NOT NULL,
  tid3 varchar(64) NOT NULL,
  tid4 varchar(64) NOT NULL,
  target_url varchar(64) NOT NULL,
  PRIMARY KEY  (id),
  KEY acct_id_ip (acct_id,ip)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_keywords (
  id int(255) NOT NULL auto_increment,
  aff_id int(255) NOT NULL default '0',
  keyword varchar(128) NOT NULL default '',
  grp int(255) NOT NULL default '0',
  url text NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_keyword_tracking (
  id int(255) NOT NULL auto_increment,
  aff_id int(255) NOT NULL default '0',
  keyword varchar(64) NOT NULL,
  tid1 varchar(64) NOT NULL,
  tid2 varchar(64) NOT NULL,
  tid3 varchar(64) NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_language_custom (
  id int(255) NOT NULL auto_increment,
  name text NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_language_custom_values (
  id int(255) NOT NULL auto_increment,
  pack_1 longtext,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_language_english (
  header_title mediumtext NOT NULL,
  header_indexLink mediumtext NOT NULL,
  header_signupLink mediumtext NOT NULL,
  header_accountLink mediumtext NOT NULL,
  header_emailLink mediumtext NOT NULL,
  header_greeting mediumtext NOT NULL,
  header_nonLogged mediumtext NOT NULL,
  header_logout mediumtext NOT NULL,
  footer_tag mediumtext NOT NULL,
  footer_copyright mediumtext NOT NULL,
  footer_rights mediumtext NOT NULL,
  index_heading_1 mediumtext NOT NULL,
  index_paragraph_1 mediumtext NOT NULL,
  index_heading_2 mediumtext NOT NULL,
  index_paragraph_2 mediumtext NOT NULL,
  index_heading_3 mediumtext NOT NULL,
  index_paragraph_3 mediumtext NOT NULL,
  index_login_title mediumtext NOT NULL,
  index_login_username mediumtext NOT NULL,
  index_login_password mediumtext NOT NULL,
  index_login_username_field mediumtext NOT NULL,
  index_login_password_field mediumtext NOT NULL,
  index_login_button mediumtext NOT NULL,
  index_login_signup_link mediumtext NOT NULL,
  index_table_title mediumtext NOT NULL,
  index_table_commission_type mediumtext NOT NULL,
  index_table_initial_deposit mediumtext NOT NULL,
  index_table_requirements mediumtext NOT NULL,
  index_table_duration mediumtext NOT NULL,
  index_table_choose mediumtext NOT NULL,
  index_table_sale mediumtext NOT NULL,
  index_table_click mediumtext NOT NULL,
  index_table_sale_text mediumtext NOT NULL,
  index_table_click_text mediumtext NOT NULL,
  index_table_deposit_tag mediumtext NOT NULL,
  index_table_requirements_tag mediumtext NOT NULL,
  index_table_duration_tag mediumtext NOT NULL,
  signup_left_column_text mediumtext NOT NULL,
  signup_left_column_title mediumtext NOT NULL,
  signup_login_title mediumtext NOT NULL,
  signup_login_username mediumtext NOT NULL,
  signup_login_password mediumtext NOT NULL,
  signup_login_password_again mediumtext NOT NULL,
  signup_login_minmax_chars mediumtext NOT NULL,
  signup_login_must_match mediumtext NOT NULL,
  signup_standard_title mediumtext NOT NULL,
  signup_standard_email mediumtext NOT NULL,
  signup_standard_company mediumtext NOT NULL,
  signup_standard_checkspayable mediumtext NOT NULL,
  signup_standard_weburl mediumtext NOT NULL,
  signup_standard_taxinfo mediumtext NOT NULL,
  signup_personal_title mediumtext NOT NULL,
  signup_personal_fname mediumtext NOT NULL,
  signup_personal_state mediumtext NOT NULL,
  signup_personal_lname mediumtext NOT NULL,
  signup_personal_phone mediumtext NOT NULL,
  signup_personal_addr1 mediumtext NOT NULL,
  signup_personal_fax mediumtext NOT NULL,
  signup_personal_addr2 mediumtext NOT NULL,
  signup_personal_zip mediumtext NOT NULL,
  signup_personal_city mediumtext NOT NULL,
  signup_personal_country mediumtext NOT NULL,
  signup_commission_title mediumtext NOT NULL,
  signup_commission_howtopay mediumtext NOT NULL,
  signup_commission_style_PPS mediumtext NOT NULL,
  signup_commission_style_PPC mediumtext NOT NULL,
  signup_paypal_optional_title mediumtext NOT NULL,
  signup_paypal_optional_payme mediumtext NOT NULL,
  signup_paypal_optional_checkbox mediumtext NOT NULL,
  signup_paypal_optional_account mediumtext NOT NULL,
  signup_paypal_optional_notes mediumtext NOT NULL,
  signup_paypal_required_title mediumtext NOT NULL,
  signup_paypal_required_account mediumtext NOT NULL,
  signup_paypal_required_notes mediumtext NOT NULL,
  signup_terms_title mediumtext NOT NULL,
  signup_terms_agree mediumtext NOT NULL,
  signup_page_button mediumtext NOT NULL,
  signup_success_email_comment mediumtext NOT NULL,
  signup_success_login_link mediumtext NOT NULL,
  custom_fields_title mediumtext NOT NULL,
  logout_msg mediumtext NOT NULL,
  signup_page_success mediumtext NOT NULL,
  login_left_column_title mediumtext NOT NULL,
  login_left_column_text mediumtext NOT NULL,
  login_title mediumtext NOT NULL,
  login_username mediumtext NOT NULL,
  login_password mediumtext NOT NULL,
  login_invalid mediumtext NOT NULL,
  login_now mediumtext NOT NULL,
  login_send_title mediumtext NOT NULL,
  login_send_username mediumtext NOT NULL,
  login_send_info mediumtext NOT NULL,
  login_send_pass mediumtext NOT NULL,
  login_send_bad mediumtext NOT NULL,
  help_new_password_heading mediumtext NOT NULL,
  help_new_password_info mediumtext NOT NULL,
  help_confirm_password_heading mediumtext NOT NULL,
  help_confirm_password_info mediumtext NOT NULL,
  help_custom_links_heading tinytext NOT NULL,
  help_custom_links_info tinytext NOT NULL,
  help_friends_footer_heading mediumtext NOT NULL,
  help_friends_footer_info mediumtext NOT NULL,
  help_friends_message_heading mediumtext NOT NULL,
  help_friends_message_info mediumtext NOT NULL,
  help_friends_subject_heading mediumtext NOT NULL,
  help_friends_subject_info mediumtext NOT NULL,
  error_title mediumtext NOT NULL,
  username_invalid mediumtext NOT NULL,
  username_taken mediumtext NOT NULL,
  username_short mediumtext NOT NULL,
  username_long mediumtext NOT NULL,
  password_invalid mediumtext NOT NULL,
  password_short mediumtext NOT NULL,
  password_long mediumtext NOT NULL,
  password_mismatch mediumtext NOT NULL,
  missing_checks mediumtext NOT NULL,
  missing_tax mediumtext NOT NULL,
  missing_fname mediumtext NOT NULL,
  missing_lname mediumtext NOT NULL,
  missing_email mediumtext NOT NULL,
  invalid_email mediumtext NOT NULL,
  missing_address mediumtext NOT NULL,
  missing_city mediumtext NOT NULL,
  missing_company mediumtext NOT NULL,
  missing_state mediumtext NOT NULL,
  missing_zip mediumtext NOT NULL,
  missing_phone mediumtext NOT NULL,
  missing_website mediumtext NOT NULL,
  missing_paypal mediumtext NOT NULL,
  missing_terms mediumtext NOT NULL,
  paypal_required mediumtext NOT NULL,
  missing_custom mediumtext NOT NULL,
  account_total_transactions mediumtext NOT NULL,
  account_standard_linking_code mediumtext NOT NULL,
  account_copy_paste mediumtext NOT NULL,
  account_not_approved mediumtext NOT NULL,
  account_suspended mediumtext NOT NULL,
  account_standard_earnings mediumtext NOT NULL,
  account_inc_bonus mediumtext NOT NULL,
  account_second_tier mediumtext NOT NULL,
  account_recurring mediumtext NOT NULL,
  account_not_available mediumtext NOT NULL,
  account_earned_todate mediumtext NOT NULL,
  menu_heading_overview mediumtext NOT NULL,
  menu_general_stats mediumtext NOT NULL,
  menu_tier_stats mediumtext NOT NULL,
  menu_payment_history mediumtext NOT NULL,
  menu_commission_details mediumtext NOT NULL,
  menu_recurring_commissions mediumtext NOT NULL,
  menu_traffic_log mediumtext NOT NULL,
  menu_heading_marketing mediumtext NOT NULL,
  menu_banners mediumtext NOT NULL,
  menu_text_ads mediumtext NOT NULL,
  menu_text_links mediumtext NOT NULL,
  menu_email_links mediumtext NOT NULL,
  menu_html_links mediumtext NOT NULL,
  menu_offline mediumtext NOT NULL,
  menu_tier_linking_code mediumtext NOT NULL,
  menu_email_friends mediumtext NOT NULL,
  menu_custom_links mediumtext NOT NULL,
  menu_heading_management mediumtext NOT NULL,
  menu_comalert mediumtext NOT NULL,
  menu_comstats mediumtext NOT NULL,
  menu_edit_account mediumtext NOT NULL,
  menu_change_pass mediumtext NOT NULL,
  menu_change_commission mediumtext NOT NULL,
  menu_heading_general_info mediumtext NOT NULL,
  menu_browse_affiliates mediumtext NOT NULL,
  menu_faq mediumtext NOT NULL,
  suspended_title mediumtext NOT NULL,
  suspended_heading mediumtext NOT NULL,
  suspended_notes mediumtext NOT NULL,
  pending_title mediumtext NOT NULL,
  pending_heading mediumtext NOT NULL,
  pending_note mediumtext NOT NULL,
  faq_title mediumtext NOT NULL,
  faq_none mediumtext NOT NULL,
  browse_title mediumtext NOT NULL,
  browse_none mediumtext NOT NULL,
  change_comm_title mediumtext NOT NULL,
  change_comm_curr_comm mediumtext NOT NULL,
  change_comm_curr_pay mediumtext NOT NULL,
  change_comm_new_comm mediumtext NOT NULL,
  change_comm_warning mediumtext NOT NULL,
  change_comm_button mediumtext NOT NULL,
  change_comm_no_other mediumtext NOT NULL,
  change_comm_level mediumtext NOT NULL,
  change_comm_updated mediumtext NOT NULL,
  password_title mediumtext NOT NULL,
  password_old_password mediumtext NOT NULL,
  password_new_password mediumtext NOT NULL,
  password_confirm_password mediumtext NOT NULL,
  password_button mediumtext NOT NULL,
  password_warning_old_missing mediumtext NOT NULL,
  password_warning_new_missing mediumtext NOT NULL,
  password_warning_mismatch mediumtext NOT NULL,
  password_warning_invalid mediumtext NOT NULL,
  password_notice mediumtext NOT NULL,
  edit_failed mediumtext NOT NULL,
  edit_success mediumtext NOT NULL,
  edit_button mediumtext NOT NULL,
  commissionstats_title mediumtext NOT NULL,
  commissionstats_info mediumtext NOT NULL,
  commissionstats_hint mediumtext NOT NULL,
  commissionstats_profile mediumtext NOT NULL,
  commissionstats_username mediumtext NOT NULL,
  commissionstats_password mediumtext NOT NULL,
  commissionstats_id mediumtext NOT NULL,
  commissionstats_source mediumtext NOT NULL,
  commissionstats_download mediumtext NOT NULL,
  commissionalert_title mediumtext NOT NULL,
  commissionalert_info mediumtext NOT NULL,
  commissionalert_hint mediumtext NOT NULL,
  commissionalert_profile mediumtext NOT NULL,
  commissionalert_username mediumtext NOT NULL,
  commissionalert_password mediumtext NOT NULL,
  commissionalert_id mediumtext NOT NULL,
  commissionalert_source mediumtext NOT NULL,
  commissionalert_download mediumtext NOT NULL,
  friends_title mediumtext NOT NULL,
  friends_info_one mediumtext NOT NULL,
  friends_info_two mediumtext NOT NULL,
  friends_info_three mediumtext NOT NULL,
  friends_heading_name mediumtext NOT NULL,
  friends_heading_email mediumtext NOT NULL,
  friends_recip_one mediumtext NOT NULL,
  friends_recip_two mediumtext NOT NULL,
  friends_recip_three mediumtext NOT NULL,
  friends_subject mediumtext NOT NULL,
  friends_body mediumtext NOT NULL,
  friends_insert mediumtext NOT NULL,
  friends_footer mediumtext NOT NULL,
  friends_chars_left mediumtext NOT NULL,
  friends_note_heading mediumtext NOT NULL,
  friends_note_one mediumtext NOT NULL,
  friends_note_two mediumtext NOT NULL,
  friends_note_three mediumtext NOT NULL,
  friends_note_four mediumtext NOT NULL,
  friends_button mediumtext NOT NULL,
  friends_footer_invalid mediumtext NOT NULL,
  friends_message_invalid mediumtext NOT NULL,
  friends_subject_invalid mediumtext NOT NULL,
  friends_recip_1_invalid_email mediumtext NOT NULL,
  friends_recip_1_invalid_name mediumtext NOT NULL,
  friends_recip_2_invalid_email mediumtext NOT NULL,
  friends_recip_2_invalid_name mediumtext NOT NULL,
  friends_recip_3_invalid_email mediumtext NOT NULL,
  friends_recip_3_invalid_name mediumtext NOT NULL,
  friends_success_one mediumtext NOT NULL,
  friends_success_two mediumtext NOT NULL,
  friends_send_again mediumtext NOT NULL,
  friends_send_again_sec mediumtext NOT NULL,
  offline_title mediumtext NOT NULL,
  offline_paragraph_one mediumtext NOT NULL,
  offline_send mediumtext NOT NULL,
  offline_page_link mediumtext NOT NULL,
  offline_paragraph_two mediumtext NOT NULL,
  banners_title mediumtext NOT NULL,
  banners_description mediumtext NOT NULL,
  ad_title mediumtext NOT NULL,
  ad_info mediumtext NOT NULL,
  links_title mediumtext NOT NULL,
  email_title mediumtext NOT NULL,
  email_group mediumtext NOT NULL,
  email_button mediumtext NOT NULL,
  email_no_group mediumtext NOT NULL,
  email_choose mediumtext NOT NULL,
  email_notice mediumtext NOT NULL,
  email_ascii mediumtext NOT NULL,
  email_html mediumtext NOT NULL,
  email_test mediumtext NOT NULL,
  email_test_info mediumtext NOT NULL,
  email_source mediumtext NOT NULL,
  html_title mediumtext NOT NULL,
  html_view_link mediumtext NOT NULL,
  traffic_title mediumtext NOT NULL,
  traffic_display mediumtext NOT NULL,
  traffic_display_visitors mediumtext NOT NULL,
  traffic_button mediumtext NOT NULL,
  traffic_title_details mediumtext NOT NULL,
  traffic_ip mediumtext NOT NULL,
  traffic_refer mediumtext NOT NULL,
  traffic_date mediumtext NOT NULL,
  traffic_time mediumtext NOT NULL,
  traffic_bottom_tag_one mediumtext NOT NULL,
  traffic_bottom_tag_two mediumtext NOT NULL,
  traffic_bottom_tag_three mediumtext NOT NULL,
  traffic_none mediumtext NOT NULL,
  traffic_no_url mediumtext NOT NULL,
  traffic_box_title mediumtext NOT NULL,
  traffic_box_info mediumtext NOT NULL,
  payment_title mediumtext NOT NULL,
  payment_date mediumtext NOT NULL,
  payment_commissions mediumtext NOT NULL,
  payment_amount mediumtext NOT NULL,
  payment_totals mediumtext NOT NULL,
  payment_none mediumtext NOT NULL,
  tier_stats_title mediumtext NOT NULL,
  tier_stats_accounts mediumtext NOT NULL,
  tier_stats_payout mediumtext NOT NULL,
  tier_stats_earnings mediumtext NOT NULL,
  tier_stats_grab_link mediumtext NOT NULL,
  tier_stats_none mediumtext NOT NULL,
  tier_stats_aff_title mediumtext NOT NULL,
  tier_stats_username mediumtext NOT NULL,
  tier_stats_current mediumtext NOT NULL,
  tier_stats_previous mediumtext NOT NULL,
  tier_stats_totals mediumtext NOT NULL,
  recurring_title mediumtext NOT NULL,
  recurring_none mediumtext NOT NULL,
  recurring_date mediumtext NOT NULL,
  recurring_status mediumtext NOT NULL,
  recurring_payout mediumtext NOT NULL,
  recurring_amount mediumtext NOT NULL,
  recurring_every mediumtext NOT NULL,
  recurring_in mediumtext NOT NULL,
  recurring_days mediumtext NOT NULL,
  recurring_total mediumtext NOT NULL,
  tlinks_title mediumtext NOT NULL,
  tlinks_embedded_one mediumtext NOT NULL,
  tlinks_embedded_two mediumtext NOT NULL,
  tlinks_embedded_current mediumtext NOT NULL,
  tlinks_embedded_type_1 mediumtext NOT NULL,
  tlinks_embedded_type_2 mediumtext NOT NULL,
  tlinks_forced_earn mediumtext NOT NULL,
  tlinks_forced_type_1 mediumtext NOT NULL,
  tlinks_forced_type_2 mediumtext NOT NULL,
  tlinks_forced_two mediumtext NOT NULL,
  tlinks_forced_code mediumtext NOT NULL,
  tlinks_forced_paste mediumtext NOT NULL,
  tlinks_forced_money mediumtext NOT NULL,
  comdetails_title mediumtext NOT NULL,
  comdetails_date mediumtext NOT NULL,
  comdetails_time mediumtext NOT NULL,
  comdetails_type mediumtext NOT NULL,
  comdetails_status mediumtext NOT NULL,
  comdetails_amount mediumtext NOT NULL,
  comdetails_additional_title mediumtext NOT NULL,
  comdetails_additional_ordnum mediumtext NOT NULL,
  comdetails_additional_saleamt mediumtext NOT NULL,
  comdetails_type_1 mediumtext NOT NULL,
  comdetails_type_2 mediumtext NOT NULL,
  comdetails_type_3 mediumtext NOT NULL,
  comdetails_type_4 mediumtext NOT NULL,
  comdetails_status_1 mediumtext NOT NULL,
  comdetails_status_2 mediumtext NOT NULL,
  comdetails_status_3 mediumtext NOT NULL,
  comdetails_not_available mediumtext NOT NULL,
  details_title mediumtext NOT NULL,
  details_drop_1 mediumtext NOT NULL,
  details_drop_2 mediumtext NOT NULL,
  details_drop_3 mediumtext NOT NULL,
  details_drop_4 mediumtext NOT NULL,
  details_drop_5 mediumtext NOT NULL,
  details_button mediumtext NOT NULL,
  details_date mediumtext NOT NULL,
  details_status mediumtext NOT NULL,
  details_commission mediumtext NOT NULL,
  details_details mediumtext NOT NULL,
  details_type_1 mediumtext NOT NULL,
  details_type_2 mediumtext NOT NULL,
  details_type_3 mediumtext NOT NULL,
  details_none mediumtext NOT NULL,
  details_no_group mediumtext NOT NULL,
  details_choose mediumtext NOT NULL,
  general_title mediumtext NOT NULL,
  general_transactions mediumtext NOT NULL,
  general_earnings_to_date mediumtext NOT NULL,
  general_history_link mediumtext NOT NULL,
  general_standard_earnings mediumtext NOT NULL,
  general_current_earnings mediumtext NOT NULL,
  general_traffic_title mediumtext NOT NULL,
  general_traffic_visitors mediumtext NOT NULL,
  general_traffic_unique mediumtext NOT NULL,
  general_traffic_sales mediumtext NOT NULL,
  general_traffic_ratio mediumtext NOT NULL,
  general_traffic_info mediumtext NOT NULL,
  general_traffic_pay_type mediumtext NOT NULL,
  general_traffic_pay_level mediumtext NOT NULL,
  general_notes_title mediumtext NOT NULL,
  general_notes_date mediumtext NOT NULL,
  general_notes_to mediumtext NOT NULL,
  general_notes_all mediumtext NOT NULL,
  general_notes_none mediumtext NOT NULL,
  contact_left_column_title mediumtext NOT NULL,
  contact_left_column_text mediumtext NOT NULL,
  contact_title mediumtext NOT NULL,
  contact_name mediumtext NOT NULL,
  contact_email mediumtext NOT NULL,
  contact_message mediumtext NOT NULL,
  contact_chars mediumtext NOT NULL,
  contact_button mediumtext NOT NULL,
  contact_received mediumtext NOT NULL,
  contact_invalid_name mediumtext NOT NULL,
  contact_invalid_email mediumtext NOT NULL,
  contact_invalid_message mediumtext NOT NULL,
  invoice_button mediumtext NOT NULL,
  invoice_header mediumtext NOT NULL,
  invoice_aff_info mediumtext NOT NULL,
  invoice_co_info mediumtext NOT NULL,
  invoice_acct_info mediumtext NOT NULL,
  invoice_payment_info mediumtext NOT NULL,
  invoice_comm_date mediumtext NOT NULL,
  invoice_comm_amt mediumtext NOT NULL,
  invoice_comm_type mediumtext NOT NULL,
  invoice_admin_note mediumtext NOT NULL,
  invoice_footer mediumtext NOT NULL,
  invoice_print mediumtext NOT NULL,
  invoice_none mediumtext NOT NULL,
  invoice_aff_id mediumtext NOT NULL,
  invoice_aff_user mediumtext NOT NULL,
  menu_pdf_marketing mediumtext NOT NULL,
  menu_pdf_training mediumtext NOT NULL,
  marketing_target_url mediumtext NOT NULL,
  marketing_source_code mediumtext NOT NULL,
  marketing_group mediumtext NOT NULL,
  banners_size mediumtext NOT NULL,
  peels_title mediumtext NOT NULL,
  peels_view mediumtext NOT NULL,
  peels_description mediumtext NOT NULL,
  lb_head_title mediumtext NOT NULL,
  lb_head_description mediumtext NOT NULL,
  lb_head_source_code mediumtext NOT NULL,
  lb_head_code_notes mediumtext NOT NULL,
  lb_head_tutorial mediumtext NOT NULL,
  lb_body_title mediumtext NOT NULL,
  lb_body_description mediumtext NOT NULL,
  lb_body_click mediumtext NOT NULL,
  lb_body_source_code mediumtext NOT NULL,
  pdf_title mediumtext NOT NULL,
  pdf_training mediumtext NOT NULL,
  pdf_marketing mediumtext NOT NULL,
  pdf_description_1 mediumtext NOT NULL,
  pdf_description_2 mediumtext NOT NULL,
  pdf_file_name mediumtext NOT NULL,
  pdf_file_size mediumtext NOT NULL,
  pdf_file_description mediumtext NOT NULL,
  pdf_bytes mediumtext NOT NULL,
  menu_heading_training_materials mediumtext NOT NULL,
  menu_videos mediumtext NOT NULL,
  menu_custom_manual mediumtext NOT NULL,
  menu_page_peels mediumtext NOT NULL,
  menu_lightboxes mediumtext NOT NULL,
  menu_email_templates mediumtext NOT NULL,
  menu_heading_custom_links mediumtext NOT NULL,
  menu_custom_reports mediumtext NOT NULL,
  menu_keyword_links mediumtext NOT NULL,
  menu_subid_links mediumtext NOT NULL,
  menu_alteranate_links mediumtext NOT NULL,
  menu_heading_additional mediumtext NOT NULL,
  menu_drop_heading_stats mediumtext NOT NULL,
  menu_drop_heading_commissions mediumtext NOT NULL,
  menu_drop_heading_history mediumtext NOT NULL,
  menu_drop_heading_traffic mediumtext NOT NULL,
  menu_drop_heading_account mediumtext NOT NULL,
  menu_drop_heading_logo mediumtext NOT NULL,
  menu_drop_heading_faq mediumtext NOT NULL,
  menu_drop_general_stats mediumtext NOT NULL,
  menu_drop_tier_stats mediumtext NOT NULL,
  menu_drop_current mediumtext NOT NULL,
  menu_drop_tier mediumtext NOT NULL,
  menu_drop_pending mediumtext NOT NULL,
  menu_drop_paid mediumtext NOT NULL,
  menu_drop_paid_rec mediumtext NOT NULL,
  menu_drop_recurring mediumtext NOT NULL,
  menu_drop_edit mediumtext NOT NULL,
  menu_drop_password mediumtext NOT NULL,
  menu_drop_change mediumtext NOT NULL,
  account_hidden mediumtext NOT NULL,
  keyword_title mediumtext NOT NULL,
  keyword_info mediumtext NOT NULL,
  keyword_heading mediumtext NOT NULL,
  keyword_tracking mediumtext NOT NULL,
  keyword_build mediumtext NOT NULL,
  keyword_example mediumtext NOT NULL,
  keyword_tutorial mediumtext NOT NULL,
  sub_tracking_title mediumtext NOT NULL,
  sub_tracking_info mediumtext NOT NULL,
  sub_tracking_build mediumtext NOT NULL,
  sub_tracking_example mediumtext NOT NULL,
  sub_tracking_tutorial mediumtext NOT NULL,
  sub_tracking_id mediumtext NOT NULL,
  alternate_title mediumtext NOT NULL,
  alternate_option_1 mediumtext NOT NULL,
  alternate_heading_1 mediumtext NOT NULL,
  alternate_info_1 mediumtext NOT NULL,
  alternate_button mediumtext NOT NULL,
  alternate_links_heading mediumtext NOT NULL,
  alternate_links_note mediumtext NOT NULL,
  alternate_links_remove mediumtext NOT NULL,
  alternate_option_2 mediumtext NOT NULL,
  alternate_info_2 mediumtext NOT NULL,
  alternate_variable mediumtext NOT NULL,
  alternate_example mediumtext NOT NULL,
  alternate_build mediumtext NOT NULL,
  alternate_none mediumtext NOT NULL,
  alternate_tutorial mediumtext NOT NULL,
  cr_title mediumtext NOT NULL,
  cr_select mediumtext NOT NULL,
  cr_button mediumtext NOT NULL,
  cr_no_results mediumtext NOT NULL,
  cr_no_results_info mediumtext NOT NULL,
  cr_used mediumtext NOT NULL,
  cr_found mediumtext NOT NULL,
  cr_times mediumtext NOT NULL,
  cr_unique mediumtext NOT NULL,
  cr_detailed mediumtext NOT NULL,
  cr_export mediumtext NOT NULL,
  cr_none mediumtext NOT NULL,
  logo_title mediumtext NOT NULL,
  logo_info mediumtext NOT NULL,
  logo_bullet_one mediumtext NOT NULL,
  logo_bullet_two mediumtext NOT NULL,
  logo_bullet_three mediumtext NOT NULL,
  logo_bullet_size_one mediumtext NOT NULL,
  logo_bullet_size_two mediumtext NOT NULL,
  logo_bullet_req_size_one mediumtext NOT NULL,
  logo_bullet_req_size_two mediumtext NOT NULL,
  logo_bullet_pixels mediumtext NOT NULL,
  logo_choose mediumtext NOT NULL,
  logo_file mediumtext NOT NULL,
  logo_browse mediumtext NOT NULL,
  logo_button mediumtext NOT NULL,
  logo_current mediumtext NOT NULL,
  logo_remove mediumtext NOT NULL,
  logo_display_status mediumtext NOT NULL,
  logo_pending mediumtext NOT NULL,
  logo_approved mediumtext NOT NULL,
  logo_success mediumtext NOT NULL,
  signup_security_title mediumtext NOT NULL,
  signup_security_info mediumtext NOT NULL,
  signup_security_code mediumtext NOT NULL,
  sub_tracking_none mediumtext NOT NULL,
  missing_security_code mediumtext NOT NULL,
  alternate_success_title mediumtext NOT NULL,
  alternate_success_info mediumtext NOT NULL,
  alternate_failed_title mediumtext NOT NULL,
  alternate_failed_info mediumtext NOT NULL,
  logo_missing_filename mediumtext NOT NULL,
  logo_required_width mediumtext NOT NULL,
  logo_required_height mediumtext NOT NULL,
  logo_maximum_width mediumtext NOT NULL,
  logo_maximum_height mediumtext NOT NULL,
  logo_size_maximum mediumtext NOT NULL,
  logo_bad_filetype mediumtext NOT NULL,
  logo_upload_error mediumtext NOT NULL,
  logo_error_title mediumtext NOT NULL,
  logo_error_bytes mediumtext NOT NULL,
  excel_title mediumtext NOT NULL,
  excel_tab_report mediumtext NOT NULL,
  excel_tab_logs mediumtext NOT NULL,
  excel_date mediumtext NOT NULL,
  excel_affiliate mediumtext NOT NULL,
  excel_criteria mediumtext NOT NULL,
  excel_link mediumtext NOT NULL,
  excel_hits mediumtext NOT NULL,
  excel_comm_stats mediumtext NOT NULL,
  excel_comm_current mediumtext NOT NULL,
  excel_comm_paid mediumtext NOT NULL,
  excel_comm_total mediumtext NOT NULL,
  excel_comm_ratio mediumtext NOT NULL,
  excel_earned mediumtext NOT NULL,
  excel_earned_current mediumtext NOT NULL,
  excel_earned_paid mediumtext NOT NULL,
  excel_earned_total mediumtext NOT NULL,
  excel_earned_tab mediumtext NOT NULL,
  excel_log_title mediumtext NOT NULL,
  excel_log_ip mediumtext NOT NULL,
  excel_log_refer mediumtext NOT NULL,
  excel_log_date mediumtext NOT NULL,
  excel_log_time mediumtext NOT NULL,
  excel_log_target mediumtext NOT NULL,
  etemplates_title mediumtext NOT NULL,
  etemplates_view_link mediumtext NOT NULL,
  etemplates_name mediumtext NOT NULL
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_language_packs (
  id int(255) NOT NULL auto_increment,
  name varchar(20) NOT NULL default '',
  status int(1) NOT NULL default '0',
  def int(1) NOT NULL default '0',
  table_name varchar(64) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_lightboxes (
  number int(3) NOT NULL auto_increment,
  grp int(10) NOT NULL default '0',
  name varchar(64) NOT NULL,
  image75 varchar(64) NOT NULL,
  image500 varchar(64) NOT NULL,
  description text NOT NULL,
  hits int(255) NOT NULL default '0',
  conv int(255) NOT NULL default '0',
  PRIMARY KEY  (number)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_links (
  id int(255) NOT NULL auto_increment,
  grp int(255) NOT NULL default '0',
  linktext text NOT NULL,
  hits int(255) NOT NULL default '0',
  conv int(255) NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_logos (
  record int(255) NOT NULL auto_increment,
  id int(255) NOT NULL default '0',
  approved int(1) NOT NULL default '0',
  filename varchar(255) NOT NULL default '',
  PRIMARY KEY  (record)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_logo_settings (
  logo_enabled int(1) NOT NULL default '0',
  logo_size int(255) NOT NULL default '0',
  logo_width int(10) NOT NULL default '0',
  logo_height int(10) NOT NULL default '0',
  logo_type int(1) NOT NULL default '0',
  logo_default varchar(255) NOT NULL default '',
  PRIMARY KEY  (logo_enabled)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_notes (
  id mediumint(255) NOT NULL auto_increment,
  note_to int(255) NOT NULL default '0',
  note_sub text NOT NULL,
  note_con text NOT NULL,
  note_display int(1) NOT NULL default '0',
  note_attach int(1) NOT NULL default '0',
  note_date varchar(24) NOT NULL default '',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_paylevels (
  id int(255) NOT NULL auto_increment,
  type int(100) NOT NULL default '0',
  level int(100) NOT NULL default '0',
  amt decimal(10,2) NOT NULL default '0.00',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_payments (
  record int(100) NOT NULL auto_increment,
  id varchar(64) NOT NULL default '',
  date date NOT NULL default '0000-00-00',
  amount decimal(10,2) NOT NULL default '0.00',
  stamp int(10) NOT NULL default '0',
  export int(1) NOT NULL default '0',
  PRIMARY KEY  (record)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_pdf (
  id int(255) NOT NULL auto_increment,
  filename text NOT NULL,
  pdf_type int(1) NOT NULL default '0',
  size int(255) NOT NULL default '0',
  pdf_desc text NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_peels (
  number int(3) NOT NULL auto_increment,
  grp int(10) NOT NULL default '0',
  name varchar(64) NOT NULL,
  image75 varchar(64) NOT NULL,
  image500 varchar(64) NOT NULL,
  description text NOT NULL,
  hits int(255) NOT NULL default '0',
  conv int(255) NOT NULL default '0',
  PRIMARY KEY  (number)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_pp_transactions (
  id int(255) NOT NULL auto_increment,
  aff_id int(255) NOT NULL default '0',
  order_num varchar(50) NOT NULL default '',
  rec int(1) NOT NULL default '0',
  date date NOT NULL default '0000-00-00',
  time time NOT NULL default '00:00:00',
  amt decimal(10,2) NOT NULL default '0.00',
  op1 varchar(64) NOT NULL default '',
  op2 varchar(64) NOT NULL default '',
  op3 varchar(64) NOT NULL default '',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_recurring (
  id int(255) NOT NULL auto_increment,
  aff_id int(255) NOT NULL default '0',
  aff_name varchar(255) NOT NULL default '',
  amount decimal(10,2) NOT NULL default '0.00',
  tracking varchar(64) NOT NULL default '',
  rec_stamp int(10) NOT NULL default '0',
  rec_now int(10) NOT NULL default '0',
  orig_date date NOT NULL default '0000-00-00',
  orig_time time NOT NULL default '00:00:00',
  pending int(1) NOT NULL default '0',
  op1 varchar(64) NOT NULL default '',
  op2 varchar(64) NOT NULL default '',
  op3 varchar(64) NOT NULL default '',
  oamount decimal(10,2) NOT NULL default '0.00',
  type int(1) NOT NULL default '0',
  profile int(2) NOT NULL default '0',
  sub_id varchar(64) NOT NULL,
  tid1 varchar(64) NOT NULL,
  tid2 varchar(64) NOT NULL,
  tid3 varchar(64) NOT NULL,
  tid4 varchar(64) NOT NULL,
  target_url varchar(255) NOT NULL,
  referring_url varchar(255) NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_rewards (
  rewards int(11) NOT NULL default '0',
  rew_1 int(11) NOT NULL default '0',
  rew_2 int(11) NOT NULL default '0',
  rew_app int(1) NOT NULL default '0'
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_sales (
  record int(100) NOT NULL auto_increment,
  id int(255) NOT NULL default '0',
  date date NOT NULL default '0000-00-00',
  time time NOT NULL default '00:00:00',
  payment decimal(20,2) NOT NULL default '0.00',
  tier int(255) NOT NULL default '0',
  top_tier_tag int(1) NOT NULL default '0',
  bonus int(1) NOT NULL default '0',
  approved int(1) NOT NULL default '0',
  ip varchar(64) NOT NULL default '',
  code bigint(12) unsigned zerofill NOT NULL default '000000000000',
  tracking varchar(64) NOT NULL default '',
  recurring int(255) NOT NULL default '0',
  tier_id int(255) NOT NULL default '0',
  rec_id int(255) NOT NULL default '0',
  op1 varchar(64) NOT NULL default '',
  op2 varchar(64) NOT NULL default '',
  op3 varchar(64) NOT NULL default '',
  amount decimal(20,2) NOT NULL default '0.00',
  type int(1) NOT NULL default '0',
  split varchar(128) NOT NULL default '',
  profile int(2) NOT NULL default '0',
  delay int(10) NOT NULL default '0',
  referring_url varchar(255) NOT NULL default '',
  adm_alert int(1) NOT NULL default '0',
  aff_alert int(1) NOT NULL default '0',
  sub_id varchar(64) NOT NULL,
  tid1 varchar(64) NOT NULL,
  tid2 varchar(64) NOT NULL,
  tid3 varchar(64) NOT NULL,
  tid4 varchar(64) NOT NULL,
  target_url varchar(255) NOT NULL,
  PRIMARY KEY  (record)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_suspensions (
  id int(255) NOT NULL auto_increment,
  affid int(255) NOT NULL default '0',
  notice mediumtext NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_terms (
  display int(1) NOT NULL default '0',
  forced int(1) NOT NULL default '0',
  terms text NOT NULL
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_tlog (
  id int(255) NOT NULL auto_increment,
  ta int(255) NOT NULL default '0',
  ti varchar(64) NOT NULL default '',
  PRIMARY KEY  (id),
  KEY ta_ti (ta,ti)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_training_videos (
  enabled int(1) NOT NULL,
  local_key blob NOT NULL,
  directory blob NOT NULL,
  address varchar(64) NOT NULL,
  payment varchar(64) NOT NULL,
  trans_id varchar(64) NOT NULL
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

mysql_query("CREATE TABLE IF NOT EXISTS idevaff_video_library (
  id int(255) NOT NULL auto_increment,
  video_name varchar(64) NOT NULL,
  video_dir blob NOT NULL,
  video_filename blob NOT NULL,
  video_query_string blob NOT NULL,
  video_size varchar(64) NOT NULL,
  video_cat int(10) NOT NULL,
  video_enabled int(1) NOT NULL default '1',
  PRIMARY KEY  (id)
) ENGINE=MyISAM");
$tabnum = $tabnum + 1;

?>